/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 swift.gltf -T -k -K -E -j -M --precision=6 
Files: swift.gltf [160.97KB] > C:\Users\Mohid\Downloads\My Projects\CarFlex1.0\client\public\assets\models\swift\swift-transformed.glb [3.75MB] (-2227%)
*/
import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";
import { useEffect, useState } from "react";

import { useCustomization } from "@contexts/Customization";

export default function Swift(props) {
  
  
  const {
    spoilerColors,
    doorColors,
    rimColors,
    windowColors,
    bonnetColors,
    lightColors,
    sideKitColors,
    bodyColors,
    bumperFrontColors,
    bumperBackColors,
    grillColors,
    fenderColors,
    diffuserColors,
    roofColors,
    trunkColors,
    // CarBody
    carBodyClick,
    setCarBodyClick,
    carBodyColor,
    setCarBodyColor,
    // Spoiler
    spoiler,
    setSpoiler,
    spoilerClick,
    setSpoilerClick,
    spoilerColor,
    setSpoilerColor,
    // Windows
    windowClick,
    setWindowClick,
    windowColor,
    setWindowColor,
    // Rims
    rimClick,
    setRimClick,
    rimColor,
    setRimColor,
    rim,
    setRim,
    // Wheels
    wheels,
    setWheels,
    wheelsClick,
    setWheelsClick,
    // Bonnet
    bonnetClick,
    setBonnetClick,
    bonnetColor,
    setBonnetColor,
    bonnet,
    setBonnet,
    // Sidekits
    sideKit,
    setSideKit,
    sideKitClick,
    setSideKitClick,
    sideKitColor,
    setSideKitColor,
    // Lights
    lightClick,
    setLightClick,
    lightColor,
    setLightColor,
    // BumperFront
    bumperFrontClick,
    setBumperFrontClick,
    bumperFrontColor,
    setBumperFrontColor,
    // BumperBack
    bumperBack,
    setBumperBack,
    bumperBackClick,
    setBumperBackClick,
    bumperBackColor,
    setBumperBackColor,
    // Grill
    grillClick,
    setGrillClick,
    grillColor,
    setGrillColor,
    // Doors
    doorClick,
    setDoorClick,
    doorColor,
    setDoorColor,
    // Engine
    engine,
    setEngine,
    engineClick,
    setEngineClick,
    // Fender
    fenderClick,
    setFenderClick,
    fenderColor,
    setFenderColor,
    // Diffuser
    diffuser,
    setDiffuser,
    diffuserClick,
    setDiffuserClick,
    diffuserColor,
    setDiffuserColor,
    // Roof
    roofClick,
    setRoofClick,
    roofColor,
    setRoofColor,
    // Silencer
    silencer,
    setSilencer,
    silencerClick,
    setSilencerClick,
    // Trunk
    trunkClick,
    setTrunkClick,
    trunkColor,
    setTrunkColor,
    door,
    setDoor,
    interior,
    interiorClick,
    setInterior,
    interiorColor,
    interiorColors,
    setInteriorClick,
    setInteriorColor,
  } = useCustomization();
  
  const group = React.useRef();
  useEffect(() => {
    setWheels(1);
    setRim(1);
    setDiffuser(0);
  }, []);

  const [tempDoor, settempDoor] = useState(door);
  useEffect(() => {
    if (interiorClick) {
      settempDoor(door);
      console.log(door);
      setDoor(6);
    } else {
      setDoor(tempDoor);
    }
  }, [interiorClick]);
  
  const { nodes, materials } = useGLTF('../../../public/assets/models/swift/swift.gltf')
 return (
    <group {...props} dispose={null}>
     <group name="Scene">
       {/* Miscellaneous */}
     <mesh name="silencer1" geometry={nodes.silencer1.geometry} material={materials.chrome_trim} rotation={[1.104903, -0.000001, Math.PI]} scale={0.001173} visible={engine !== 2} />
     <mesh name="skeleton" geometry={nodes.skeleton.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
     <mesh name="back_tyres_inner_cover" geometry={nodes.back_tyres_inner_cover.geometry} material={materials.interior} position={[0, -0.013621, 0.002051]} rotation={[-0.010147, 0, 0]} scale={0.001729} visible={engine != 2} />
       {/* Bumper Back */}
       <mesh name="bumper_b" geometry={nodes.bumper_b.geometry} material={materials.body} scale={0.001729} visible={engine!=2}><meshStandardMaterial
  color={bumperBackColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  visible={true}
/></mesh>


       {/* Engine */}
       <group name="engine1_f" position={[0, 0.823026, 2.257341]} scale={[1.845896, 1.41992, 1.703904]} visible={engine===1}>
          <mesh name="Car_2-Turbo_V6_Engine_Asembly_Designing" geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing'].geometry} material={materials.engine_Base} />
          <mesh name="Car_2-Turbo_V6_Engine_Asembly_Designing_1" geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_1'].geometry} material={materials.engine_body} />
          <mesh name="Car_2-Turbo_V6_Engine_Asembly_Designing_2" geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_2'].geometry} material={materials.engine_body_dark} />
          <mesh name="Car_2-Turbo_V6_Engine_Asembly_Designing_3" geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_3'].geometry} material={materials.front_grill} />
          <mesh name="Car_2-Turbo_V6_Engine_Asembly_Designing_4" geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_4'].geometry} material={materials.engine_filters} />
          <mesh name="Car_2-Turbo_V6_Engine_Asembly_Designing_5" geometry={nodes['Car_2-Turbo_V6_Engine_Asembly_Designing_5'].geometry} material={materials.engine_pipes} />
        </group>

        <group name="engine2_b" rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.650992} visible={engine===2}>
          <mesh name="engine" geometry={nodes.engine.geometry} material={materials['Body.black']} />
          <mesh name="engine_1" geometry={nodes.engine_1.geometry} material={materials['Carbon.001']} />
          <mesh name="engine_2" geometry={nodes.engine_2.geometry} material={materials.pipe1} />
          <mesh name="engine_3" geometry={nodes.engine_3.geometry} material={materials.copper} />
          <mesh name="engine_4" geometry={nodes.engine_4.geometry} material={materials.airfilter_black} />
          <mesh name="engine_5" geometry={nodes.engine_5.geometry} material={materials.roughpot} />
          <mesh name="engine_6" geometry={nodes.engine_6.geometry} material={materials['copper.001']} />
          <mesh name="engine_7" geometry={nodes.engine_7.geometry} material={materials.metalframe} />
          <mesh name="engine_8" geometry={nodes.engine_8.geometry} material={materials.undercarriage} />
          <mesh name="engine_9" geometry={nodes.engine_9.geometry} material={materials.red_glow} />
       </group>
       
        {/* Rim and Tyres */}
        {/* Rim 1 */}
        <group name="swift_rim1_bl" position={[1.532877, 0.360791, -2.493615]} scale={0.001729} visible={rim===1}>
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002.geometry} material={materials.rim_silver} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002_1" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002_1.geometry} material={materials.rim_red} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002_2" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002_2.geometry} material={materials.chrome_trim} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002_3" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M002_3.geometry} material={materials.interior} />
        </group>

        <group name="swift_rim1_br" position={[-1.525675, 0.360223, -2.493774]} scale={0.001729} visible={rim===1}>
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001.geometry} material={materials.rim_silver} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001_1" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001_1.geometry} material={materials.rim_red} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001_2" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001_2.geometry} material={materials.chrome_trim} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001_3" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M001_3.geometry} material={materials.interior} />
        </group>

        <group name="swift_rim1_fr" position={[-1.52565, 0.360389, 2.030861]} scale={0.001729} visible={rim===1}>
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003.geometry} material={materials.rim_silver} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003_1" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003_1.geometry} material={materials.rim_red} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003_2" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003_2.geometry} material={materials.chrome_trim} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003_3" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M003_3.geometry} material={materials.interior} />
        </group>

        <group name="swift_rim1_fl" scale={0.001729} visible={rim===1}>
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M.geometry} material={materials.rim_silver} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M_1" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M_1.geometry} material={materials.rim_red} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M_2" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M_2.geometry} material={materials.chrome_trim} />
          <mesh name="Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M_3" geometry={nodes.Mesh5_M_2022_Suzuki_Swift_SWIFT_ZP_EX_WHEEL_CHROME_PLATED_M_3.geometry} material={materials.interior} />
        </group>

        {/* Tyre 1 */}
        <mesh name="swift_tyre1_bl" geometry={nodes.swift_tyre1_bl.geometry} material={materials.airfilter_black} position={[1.390158, 0.376274, -2.499197]} scale={0.001729}  visible={wheels === 1}/>

        <mesh name="swift_tyre1_br" geometry={nodes.swift_tyre1_br.geometry} material={materials.airfilter_black} position={[-1.384654, 0.373742, -2.496929]} scale={0.001729}  visible={wheels === 1}/>

        <mesh name="swift_tyre1_fr" geometry={nodes.swift_tyre1_fr.geometry} material={materials.airfilter_black} position={[-1.37496, 0.375666, 2.025035]} scale={0.001729} visible={wheels === 1} />
        
        <mesh name="swift_tyre1_fl" geometry={nodes.swift_tyre1_fl.geometry} material={materials.airfilter_black} position={[1.382389, 0.379188, 2.026088]} scale={0.001729} visible={wheels===1} />

        {/* Rim 2 */}
        <mesh name="swift_rim2_fr" geometry={nodes.swift_rim2_fr.geometry} material={materials.copper} position={[-1.608342, 0.494032, 2.038511]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.777735, 0.933756, 0.777348]} visible={rim === 2} material-color={rimColor.color} />
        
        <mesh name="swift_rim2_br" geometry={nodes.swift_rim2_br.geometry} material={materials.copper} position={[-1.579921, 0.494032, -2.513051]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.777735, 0.933756, 0.777348]} visible={rim===2} />
        
        <mesh name="swift_rim2_bl" geometry={nodes.swift_rim2_bl.geometry} material={materials.copper} position={[1.581444, 0.494032, -2.513051]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.777735, 0.933757, 0.777348]} visible={rim === 2} />

        <mesh name="swift_rim2_fl" geometry={nodes.swift_rim2_fl.geometry} material={materials.copper} position={[1.611358, 0.494032, 2.038511]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.777735, 0.933756, 0.777348]} visible={rim===2} />
        
       {/* Tyre 2 */}
        <mesh name="swift_tyre2_bl" geometry={nodes.swift_tyre2_bl.geometry} material={materials.airfilter_black} position={[1.47629, 0.494032, -2.513029]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01758, 0.022474, 0.01758]} visible={wheels===2} />
        
        <mesh name="swift_tyre2_fl" geometry={nodes.swift_tyre2_fl.geometry} material={materials.airfilter_black} position={[1.506178, 0.494032, 2.038508]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.01758, 0.022474, 0.01758]} visible={wheels === 2} />
        
        <mesh name="swift_tyre2_fr" geometry={nodes.swift_tyre2_fr.geometry} material={materials.airfilter_black} position={[-1.50312, 0.494032, 2.038508]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01758, 0.022474, 0.01758]} visible={wheels===2} />

        <mesh name="swift_tyre2_br" geometry={nodes.swift_tyre2_br.geometry} material={materials.airfilter_black} position={[-1.474766, 0.494032, -2.513029]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01758, 0.022474, 0.01758]} visible={wheels===2} />
        
        {/* Disc */}
        <mesh name="disc_br" geometry={nodes.disc_br.geometry} material={materials['Carbon Fiber']} position={[-1.395351, 0.374439, -2.50535]} scale={[0.001729, 0.002488, 0.002488]} visible={wheels===1} />
        <mesh name="disc_fr" geometry={nodes.disc_fr.geometry} material={materials['Carbon Fiber']} position={[-1.395351, 0.381628, 2.018453]} scale={[0.001729, 0.002488, 0.002488]} visible={wheels===1}/>
        <mesh name="disc_bl" geometry={nodes.disc_bl.geometry} material={materials['Carbon Fiber']} position={[1.402337, 0.374439, -2.505349]} scale={[0.001729, 0.002488, 0.002488]} visible={wheels===1}/>
        <mesh name="disc_fl" geometry={nodes.disc_fl.geometry} material={materials['Carbon Fiber']} position={[1.402337, 0.381628, 2.018454]} scale={[0.001729, 0.002488, 0.002488]} visible={wheels===1}/>

        {/* Windows */}
        
      <group name="windows_f_b" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="windows_f_b_1" geometry={nodes.windows_f_b_1.geometry} material={materials.lights_glass} material-color={windowColor.color}material-opacity={0.8} material-transparent={true} />
          <mesh name="windows_f_b_2" geometry={nodes.windows_f_b_2.geometry} material={materials.defrost_lines} />
          <mesh name="windows_f_b_3" geometry={nodes.windows_f_b_3.geometry} material={materials.plastic} />
        </group>
        <mesh name="windows_r_l" geometry={nodes.windows_r_l.geometry} material={materials.lights_glass} material-opacity={0.8} material-transparent={true} material-color={windowColor.color} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <group name="windowshade" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="windowshade_1" geometry={nodes.windowshade_1.geometry} material={materials.body} />
          <mesh name="windowshade_2" geometry={nodes.windowshade_2.geometry} material={materials.plastic} />
        </group>
        <mesh name="wipers_f_b" geometry={nodes.wipers_f_b.geometry} material={materials.plastic} rotation={[-0.010521, 0, 0]} scale={0.001729} />
      {/* Fender */}
      <group name="fender_b" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="fender_r" geometry={nodes.fender_r.geometry} material={materials.body} ><meshStandardMaterial
  color={fenderColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  visible={true}
/></mesh>
          <mesh name="fender_r_1" geometry={nodes.fender_r_1.geometry} material={materials.plastic} material-color="black" />
        </group>
        <group name="fender_f" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="fender_f_1" geometry={nodes.fender_f_1.geometry} material={materials.body} ><meshStandardMaterial
  color={fenderColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  visible={true}
/></mesh>
          <mesh name="fender_f_2" geometry={nodes.fender_f_2.geometry} material={materials.plastic} />
        </group>
      {/* Roof */}
      <group name="roof" rotation={[-0.010475, 0, 0]} scale={0.001729}>
          <mesh name="roof_1" geometry={nodes.roof_1.geometry} material={materials.body} ><meshStandardMaterial
  color={roofColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  visible={true}
/></mesh>
          <mesh name="roof_2" geometry={nodes.roof_2.geometry} material={materials.plastic} />
        </group>
      {/* Trunk */}
<group name="trunk" scale={0.001729}>
          <mesh name="trunk_1" geometry={nodes.trunk_1.geometry} material={materials.body}><meshStandardMaterial
  color={trunkColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  visible={true}
/></mesh>
          <mesh name="trunk_2" geometry={nodes.trunk_2.geometry} material={materials.chrome_trim} />
        </group>

{/* Bonnet */}
      <mesh name="bonnet_closed" geometry={nodes.bonnet_closed.geometry} material={materials.body} rotation={[-0.010521, 0, 0]} scale={0.001729} ><meshStandardMaterial
  color={bonnetColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  visible={bonnet==1}
/>
</mesh>
        <mesh name="bonnet_opened" geometry={nodes.bonnet_opened.geometry} material={materials.body} position={[-1.133537, 1.65239, 1.708919]} rotation={[-1.160121, 0, 0]} scale={0.001729} ><meshStandardMaterial
  color={bonnetColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  visible={bonnet==0}
/>
      </mesh>
      {/* Bumper_f */}
      <group name="bumper_f" rotation={[-0.010521, 0, 0]} scale={0.001729}>
        <mesh name="bumper_f_1" geometry={nodes.bumper_f_1.geometry} material={materials.body} >
          <meshStandardMaterial
  color={bumperFrontColor.color}
  emissive="#000000"
  emissiveIntensity={1}
  metalness={0.6323829889297485}
  roughness={0.7548746466636658}
  opacity={1}
  transparent={false}
  side={2}
  wireframe={false}
  flatShading={false}
  
/>
      </mesh>
          <mesh name="bumper_f_2" geometry={nodes.bumper_f_2.geometry} material={materials.interior} material-color={interiorColor.color} />
          <mesh name="bumper_f_3" geometry={nodes.bumper_f_3.geometry} material={materials.plastic}   />
          <mesh name="bumper_f_4" geometry={nodes.bumper_f_4.geometry} material={materials.front_grill} material-color={grillColor.color} />
          <mesh name="bumper_f_5" geometry={nodes.bumper_f_5.geometry} material={materials.chrome_trim} material-color={grillColor.color}  />
       </group>
       
       {/* Spoilers */}
       <mesh name="spoiler1_roof" geometry={nodes.spoiler1_roof.geometry} material={materials['Carbon Fiber']} rotation={[0.996874, 0, 0]} scale={[0.034199, 0.048198, 0.048198]} visible={spoiler===1} ><meshPhysicalMaterial color = {spoilerColor.color}
  emissive= "000000"
  emissiveIntensity= {1}
  metalness= {1}
  roughness= {1}
  opacity= {1}
  transparent= {false}
  side= {2}
  wireframe= {false}
  flatShading= {false}
  visible= {true}></meshPhysicalMaterial></mesh>
        <mesh name="spoiler2_rear" geometry={nodes.spoiler2_rear.geometry} material={materials['Carbon Fiber']} rotation={[1.62012, 0, 0]} scale={1.619505} visible={spoiler===2} ><meshPhysicalMaterial color = {spoilerColor.color}
  emissive= "000000"
  emissiveIntensity= {1}
  metalness= {1}
  roughness= {1}
  opacity= {1}
  transparent= {false}
  side= {2}
  wireframe= {false}
  flatShading= {false}
  visible= {true}></meshPhysicalMaterial></mesh>
      
       {/* SideSkirt - Sidekit Fendor Flares */}
       <mesh name="fendor_flares" geometry={nodes.fendor_flares.geometry} material={materials['Carbon Fiber']} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.674832, 0.674832, 0.674832]} visible={sideKit === 2 || sideKit == 5} ><meshPhysicalMaterial color = {sideKitColor.color}
  emissive= "000000"
  emissiveIntensity= {1}
  metalness= {1}
  roughness= {1}
  opacity= {1}
  transparent= {false}
  side= {2}
  wireframe= {false}
  flatShading= {false}
  visible= {true}></meshPhysicalMaterial></mesh>
        <mesh name="side_skirts" geometry={nodes.side_skirts.geometry} material={materials['Carbon Fiber']} scale={[-0.127324, 1, 1]} visible={sideKit == 1 || sideKit == 2 || sideKit == 4 || sideKit == 5} ><meshPhysicalMaterial color = {sideKitColor.color}
  emissive= "000000"
  emissiveIntensity= {1}
  metalness= {1}
  roughness= {1}
  opacity= {1}
  transparent= {false}
  side= {2}
  wireframe= {false}
  flatShading= {false}
  visible= {true}></meshPhysicalMaterial></mesh>
        <mesh name="splitter_f" geometry={nodes.splitter_f.geometry} material={materials['Carbon Fiber']} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.674832, 0.674832, 0.674832]} visible={sideKit === 3 || sideKit === 4 || sideKit === 5}  ><meshPhysicalMaterial color = {sideKitColor.color}
  emissive= "000000"
  emissiveIntensity= {1}
  metalness= {1}
  roughness= {1}
  opacity= {1}
  transparent= {false}
  side= {2}
  wireframe= {false}
  flatShading= {false}
  visible= {true}></meshPhysicalMaterial></mesh>
      {/* Remaining */}
      
      
        

        
        
       
        
        <group name="door_bl_close" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="door_bl" geometry={nodes.door_bl.geometry} material={materials.body} />
          <mesh name="door_bl_1" geometry={nodes.door_bl_1.geometry} material={materials.interior} />
          <mesh name="door_bl_2" geometry={nodes.door_bl_2.geometry} material={materials.plastic} />
        </group>
        <group name="door_bl_open" position={[1.287782, 1.101864, -0.566193]} rotation={[0.746531, -1.331984, 0.762752]} scale={0.001729}>
          <mesh name="door_bl001" geometry={nodes.door_bl001.geometry} material={materials.body} />
          <mesh name="door_bl001_1" geometry={nodes.door_bl001_1.geometry} material={materials.interior} />
          <mesh name="door_bl001_2" geometry={nodes.door_bl001_2.geometry} material={materials.plastic} />
        </group>
        <group name="door_br_close" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="door_br" geometry={nodes.door_br.geometry} material={materials.body} />
          <mesh name="door_br_1" geometry={nodes.door_br_1.geometry} material={materials.interior} />
          <mesh name="door_br_2" geometry={nodes.door_br_2.geometry} material={materials.plastic} />
        </group>
        <group name="door_br_open" position={[-1.287706, 1.101863, -0.566193]} rotation={[0.746531, 1.331984, -0.762752]} scale={0.001729}>
          <mesh name="door_br001" geometry={nodes.door_br001.geometry} material={materials.body} />
          <mesh name="door_br001_1" geometry={nodes.door_br001_1.geometry} material={materials.interior} />
          <mesh name="door_br001_2" geometry={nodes.door_br001_2.geometry} material={materials.plastic} />
        </group>
        <group name="door_fl_close" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="door_fl" geometry={nodes.door_fl.geometry} material={materials.body} />
          <mesh name="door_fl_1" geometry={nodes.door_fl_1.geometry} material={materials.interior} />
          <mesh name="door_fl_2" geometry={nodes.door_fl_2.geometry} material={materials.plastic} />
        </group>
        <group name="door_fl_open" position={[1.348255, 1.356961, 1.092892]} rotation={[-0.024891, -1.134345, -0.022559]} scale={0.001729}>
          <mesh name="door_fl003" geometry={nodes.door_fl003.geometry} material={materials.body} />
          <mesh name="door_fl003_1" geometry={nodes.door_fl003_1.geometry} material={materials.interior} />
          <mesh name="door_fl003_2" geometry={nodes.door_fl003_2.geometry} material={materials.plastic} />
          <mesh name="door_fl003_3" geometry={nodes.door_fl003_3.geometry} material={materials.turn_signals} />
          <mesh name="door_fl003_4" geometry={nodes.door_fl003_4.geometry} material={materials.side_mirrors_glass} />
        </group>
        <group name="door_fr_close" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="door_fr" geometry={nodes.door_fr.geometry} material={materials.body} />
          <mesh name="door_fr_1" geometry={nodes.door_fr_1.geometry} material={materials.interior} />
          <mesh name="door_fr_2" geometry={nodes.door_fr_2.geometry} material={materials.plastic} />
        </group>
        <group name="door_fr_open" position={[-1.348708, 1.356962, 1.092947]} rotation={[-0.024891, 1.134345, 0.022559]} scale={0.001729}>
          <mesh name="door_fr001" geometry={nodes.door_fr001.geometry} material={materials.body} />
          <mesh name="door_fr001_1" geometry={nodes.door_fr001_1.geometry} material={materials.interior} />
          <mesh name="door_fr001_2" geometry={nodes.door_fr001_2.geometry} material={materials.plastic} />
          <mesh name="door_fr001_3" geometry={nodes.door_fr001_3.geometry} material={materials.turn_signals} />
          <mesh name="door_fr001_4" geometry={nodes.door_fr001_4.geometry} material={materials.side_mirrors_glass} />
        </group>
        
        <mesh name="interior" geometry={nodes.interior.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <group name="lights_b" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="breaklights" geometry={nodes.breaklights.geometry} material={materials.brake_glass} />
          <mesh name="breaklights_1" geometry={nodes.breaklights_1.geometry} material={materials.lights_red} />
          <mesh name="breaklights_2" geometry={nodes.breaklights_2.geometry} material={materials.lights_brake_drl} />
          <mesh name="breaklights_3" geometry={nodes.breaklights_3.geometry} material={materials.lights_turn} />
        </group>
        <group name="lights_f" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="headlights" geometry={nodes.headlights.geometry} material={materials.lights_inside_black} />
          <mesh name="headlights_1" geometry={nodes.headlights_1.geometry} material={materials.lights_inside_white} />
          <mesh name="headlights_2" geometry={nodes.headlights_2.geometry} material={materials.lights_white_bulb} />
          <mesh name="headlights_3" geometry={nodes.headlights_3.geometry} material={materials.lights_yellow_bulb} />
          <mesh name="headlights_4" geometry={nodes.headlights_4.geometry} material={materials.lights_drl} />
          <mesh name="headlights_5" geometry={nodes.headlights_5.geometry} material={materials.lights_glass} />
        </group>
        <group name="lights_fog" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="foglights" geometry={nodes.foglights.geometry} material={materials.lights_drl} />
          <mesh name="foglights_1" geometry={nodes.foglights_1.geometry} material={materials.lights_glass} />
          <mesh name="foglights_2" geometry={nodes.foglights_2.geometry} material={materials.lights_yellow_bulb} />
        </group>
        
        <mesh name="seat_b" geometry={nodes.seat_b.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="seat_fl" geometry={nodes.seat_fl.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="seat_fr" geometry={nodes.seat_fr.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />

        <group name="sidemirror_l" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="sidemirror_l_1" geometry={nodes.sidemirror_l_1.geometry} material={materials.body} />
          <mesh name="sidemirror_l_2" geometry={nodes.sidemirror_l_2.geometry} material={materials.turn_signals} />
          <mesh name="sidemirror_l_3" geometry={nodes.sidemirror_l_3.geometry} material={materials.plastic} />
          <mesh name="sidemirror_l_4" geometry={nodes.sidemirror_l_4.geometry} material={materials.side_mirrors_glass} />
        </group>

        <group name="sidemirror_r" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="sidemirror_r_1" geometry={nodes.sidemirror_r_1.geometry} material={materials.body} />
          <mesh name="sidemirror_r_2" geometry={nodes.sidemirror_r_2.geometry} material={materials.turn_signals} />
          <mesh name="sidemirror_r_3" geometry={nodes.sidemirror_r_3.geometry} material={materials.plastic} />
          <mesh name="sidemirror_r_4" geometry={nodes.sidemirror_r_4.geometry} material={materials.side_mirrors_glass} />
        </group>

       
        

        
        
      </group>
    </group>
  )
}


useGLTF.preload('../../../public/assets/models/swift/swift.gltf')
