/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 swift.gltf -T -k -K -E -j -M --precision=6 
Files: swift.gltf [124.12KB] > C:\Users\Mohid\Downloads\My Projects\CarFlex1.0\client\public\assets\models\swift-transformed.glb [3.03MB] (-2338%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../../../public/assets/models/swift.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="body" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body_1" geometry={nodes.body_1.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} />
          <mesh name="body_2" geometry={nodes.body_2.geometry} material={materials.body} />
          <mesh name="body_3" geometry={nodes.body_3.geometry} material={materials.interior} />
          <mesh name="body_4" geometry={nodes.body_4.geometry} material={materials.windows} />
          <mesh name="body_5" geometry={nodes.body_5.geometry} material={materials.wipers} />
        </group>
        <mesh name="body001" geometry={nodes.body001.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <group name="body002" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body022" geometry={nodes.body022.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} />
          <mesh name="body022_1" geometry={nodes.body022_1.geometry} material={materials.interior} />
          <mesh name="body022_2" geometry={nodes.body022_2.geometry} material={materials.side_mirrors_glass} />
        </group>
        <mesh name="body003" geometry={nodes.body003.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="bonnet" geometry={nodes.bonnet.geometry} material={materials.body} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="bumper_b" geometry={nodes.bumper_b.geometry} material={materials.body} scale={0.001729} />
        <group name="bumper_f" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body015" geometry={nodes.body015.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} />
          <mesh name="body015_1" geometry={nodes.body015_1.geometry} material={materials.body} />
        </group>
        <group name="bumper_f_plastic" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body020" geometry={nodes.body020.geometry} material={materials.body} />
          <mesh name="body020_1" geometry={nodes.body020_1.geometry} material={materials.plastic} />
          <mesh name="body020_2" geometry={nodes.body020_2.geometry} material={materials.chrome_trim} />
          <mesh name="body020_3" geometry={nodes.body020_3.geometry} material={materials.interior} />
          <mesh name="body020_4" geometry={nodes.body020_4.geometry} material={materials.front_grill} />
        </group>
        <group name="door_bl" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body013" geometry={nodes.body013.geometry} material={materials.body} />
          <mesh name="body013_1" geometry={nodes.body013_1.geometry} material={materials.interior} />
        </group>
        <group name="door_br" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body012" geometry={nodes.body012.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} />
          <mesh name="body012_1" geometry={nodes.body012_1.geometry} material={materials.body} />
          <mesh name="body012_2" geometry={nodes.body012_2.geometry} material={materials.interior} />
        </group>
        <group name="door_f" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body006" geometry={nodes.body006.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} >
  <meshPhysicalMaterial color="hotpink" />
</mesh>
          <mesh name="body006_1" geometry={nodes.body006_1.geometry} material={materials.body} >
  <meshPhysicalMaterial color="hotpink" />
</mesh>
          <mesh name="body006_2" geometry={nodes.body006_2.geometry} material={materials.interior} >
 
</mesh>
          <mesh name="body006_3" geometry={nodes.body006_3.geometry} material={materials.side_mirrors_glass} >
  <meshPhysicalMaterial color="hotpink" />
</mesh>
        </group>
        <group name="engine" rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.650992}>
          <mesh name="engine_1" geometry={nodes.engine_1.geometry} material={materials['Body.black']} />
          <mesh name="engine_2" geometry={nodes.engine_2.geometry} material={materials['Carbon.001']} />
          <mesh name="engine_3" geometry={nodes.engine_3.geometry} material={materials.pipe1} />
          <mesh name="engine_4" geometry={nodes.engine_4.geometry} material={materials.copper} />
          <mesh name="engine_5" geometry={nodes.engine_5.geometry} material={materials.airfilter_black} />
          <mesh name="engine_6" geometry={nodes.engine_6.geometry} material={materials.roughpot} />
          <mesh name="engine_7" geometry={nodes.engine_7.geometry} material={materials['copper.001']} />
          <mesh name="engine_8" geometry={nodes.engine_8.geometry} material={materials.metalframe} />
          <mesh name="engine_9" geometry={nodes.engine_9.geometry} material={materials.undercarriage} />
          <mesh name="engine_10" geometry={nodes.engine_10.geometry} material={materials.red_glow} />
        </group>
        <group name="fender_f" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body002_1" geometry={nodes.body002_1.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} />
          <mesh name="body002_2" geometry={nodes.body002_2.geometry} material={materials.body} />
          <mesh name="body002_3" geometry={nodes.body002_3.geometry} material={materials.interior} />
        </group>
        <mesh name="fender_l" geometry={nodes.fender_l.geometry} material={materials.body} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="fender_r" geometry={nodes.fender_r.geometry} material={materials.body} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <group name="lights_b" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="breaklights" geometry={nodes.breaklights.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_TAILLIGHT_READGLASS_MAT} />
          <mesh name="breaklights_1" geometry={nodes.breaklights_1.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_TAILLIGHT_WHITE_REFLECTO} />
          <mesh name="breaklights_2" geometry={nodes.breaklights_2.geometry} material={materials.turn_signals} />
          <mesh name="breaklights_3" geometry={nodes.breaklights_3.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_TAILLIGHT_RED_REFLECTORS} />
          <mesh name="breaklights_4" geometry={nodes.breaklights_4.geometry} material={materials['Material.001']} />
          <mesh name="breaklights_5" geometry={nodes.breaklights_5.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_TAILLIGHT_CHROME_MAT} />
          <mesh name="breaklights_6" geometry={nodes.breaklights_6.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_ORRANGE_BULB_MAT} />
          <mesh name="breaklights_7" geometry={nodes.breaklights_7.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_TAILLIGHT_READ_GLASS_MAT} />
          <mesh name="breaklights_8" geometry={nodes.breaklights_8.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_PARTS_BREAKLIGHT_MAT} />
        </group>
        <group name="lights_f" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="headlights" geometry={nodes.headlights.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_HEADLIGHT_BLACKPLASTIC_M} />
          <mesh name="headlights_1" geometry={nodes.headlights_1.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_ORRANGE_BULB_MAT} />
          <mesh name="headlights_2" geometry={nodes.headlights_2.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_HEADLIGHT_LED_MAT} />
          <mesh name="headlights_3" geometry={nodes.headlights_3.geometry} material={materials.windows} />
          <mesh name="headlights_4" geometry={nodes.headlights_4.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_HEADLIGHT_HALOGEN_MAT} />
          <mesh name="headlights_5" geometry={nodes.headlights_5.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LILGHTS_HEADLIGHT_SHINEYCHROME_} />
          <mesh name="headlights_6" geometry={nodes.headlights_6.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LIGHTS_HEADLIGHT_CHROME_MAT} />
        </group>
        <group name="lights_fog" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="foglights" geometry={nodes.foglights.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZP_EX_LILGHTS_HEADLIGHT_SHINEYCHROME_} />
          <mesh name="foglights_1" geometry={nodes.foglights_1.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_Z_EX_LIGHTS_HEADLIGHT_GLASS_MAT} />
          <mesh name="foglights_2" geometry={nodes.foglights_2.geometry} material={materials.turn_signals} />
        </group>
        <mesh name="logo_b_(bodyblackchrome)" geometry={nodes['logo_b_(bodyblackchrome)'].geometry} material={materials.chrome_trim} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="logo_f_(bodyblackchrome)" geometry={nodes['logo_f_(bodyblackchrome)'].geometry} material={materials.chrome_trim} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <group name="radiator_fr" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body014" geometry={nodes.body014.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} />
          <mesh name="body014_1" geometry={nodes.body014_1.geometry} material={materials.front_grill} />
        </group>
        <group name="roof" rotation={[-0.010475, 0, 0]} scale={0.001729}>
          <mesh name="roof001" geometry={nodes.roof001.geometry} material={materials.body} />
          <mesh name="roof001_1" geometry={nodes.roof001_1.geometry} material={materials.interior} />
        </group>
        <mesh name="seat_b1" geometry={nodes.seat_b1.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="seat_fl" geometry={nodes.seat_fl.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="seat_fr" geometry={nodes.seat_fr.geometry} material={materials.interior} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <mesh name="side_skirts" geometry={nodes.side_skirts.geometry} material={materials['Carbon Fiber']} scale={[-0.127324, 1, 1]} />
        <group name="sidemirror_l" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body010" geometry={nodes.body010.geometry} material={materials.body} />
          <mesh name="body010_1" geometry={nodes.body010_1.geometry} material={materials.turn_signals} />
          <mesh name="body010_2" geometry={nodes.body010_2.geometry} material={materials.interior} />
          <mesh name="body010_3" geometry={nodes.body010_3.geometry} material={materials.side_mirrors_glass} />
        </group>
        <group name="sidemirror_r" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="body003_1" geometry={nodes.body003_1.geometry} material={materials.body} />
          <mesh name="body003_2" geometry={nodes.body003_2.geometry} material={materials.turn_signals} />
          <mesh name="body003_3" geometry={nodes.body003_3.geometry} material={materials.interior} />
          <mesh name="body003_4" geometry={nodes.body003_4.geometry} material={materials.side_mirrors_glass} />
        </group>
        <mesh name="splitter_fr_supports" geometry={nodes.splitter_fr_supports.geometry} material={materials['Carbon Fiber']} rotation={[0, 0, -Math.PI / 2]} scale={[0.214883, 0.541241, 0.075907]} />
        <mesh name="spoiler" geometry={nodes.spoiler.geometry} material={materials['Carbon Fiber']} rotation={[1.62012, 0, 0]} scale={1.619505} />
        <mesh name="trunk" geometry={nodes.trunk.geometry} material={materials.body} scale={0.001729} />
        <group name="undertrays" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="undertrays_1" geometry={nodes.undertrays_1.geometry} material={materials.M_2022_Suzuki_Swift_SWIFT_ZXIP_GAPFILL_MAT} />
          <mesh name="undertrays_2" geometry={nodes.undertrays_2.geometry} material={materials.interior} />
        </group>
        <mesh name="widebody_kit" geometry={nodes.widebody_kit.geometry} material={materials['Carbon Fiber']} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-0.674832, 0.674832, 0.674832]} />
        <group name="windows_f_b" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="windows_f_b_1" geometry={nodes.windows_f_b_1.geometry} material={materials.windows} />
          <mesh name="windows_f_b_2" geometry={nodes.windows_f_b_2.geometry} material={materials.defrost_lines} />
        </group>
        <mesh name="windows_r_l" geometry={nodes.windows_r_l.geometry} material={materials.windows} rotation={[-0.010521, 0, 0]} scale={0.001729} />
        <group name="windowshade" rotation={[-0.010521, 0, 0]} scale={0.001729}>
          <mesh name="windowshade_1" geometry={nodes.windowshade_1.geometry} material={materials.body} />
          <mesh name="windowshade_2" geometry={nodes.windowshade_2.geometry} material={materials.interior} />
        </group>
        <mesh name="swift_rim1_fr" geometry={nodes.swift_rim1_fr.geometry} material={materials.copper} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.701254, 0.841933, 0.700905]} />
        <mesh name="swift_tyre1_fr" geometry={nodes.swift_tyre1_fr.geometry} material={materials.airfilter_black} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.015852, 0.020264, 0.015852]} />
        <mesh name="swift_rim1_fl" geometry={nodes.swift_rim1_fl.geometry} material={materials.copper} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.701254, 0.841933, 0.700905]} />
        <mesh name="swift_tyre1_fl" geometry={nodes.swift_tyre1_fl.geometry} material={materials.airfilter_black} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.015852, 0.020264, 0.015852]} />
        <mesh name="swift_rim1_br" geometry={nodes.swift_rim1_br.geometry} material={materials.copper} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.701254, 0.841933, 0.700905]} />
        <mesh name="swift_tyre1_br" geometry={nodes.swift_tyre1_br.geometry} material={materials.airfilter_black} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.015852, 0.020264, 0.015852]} />
        <mesh name="swift_rim1_bl" geometry={nodes.swift_rim1_bl.geometry} material={materials.copper} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.701254, 0.841933, 0.700905]} />
        <mesh name="swift_tyre1_bl" geometry={nodes.swift_tyre1_bl.geometry} material={materials.airfilter_black} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[-0.015852, 0.020264, 0.015852]} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../public/assets/models/swift.gltf')
